kind: pipeline
name: default

steps:
- name: test
  image: squidfunk/mkdocs-material
  commands:
  - pip install -r requirements.txt
  - mkdocs build

- name: update
  image: appleboy/drone-git-push
    settings:
      remote_name: origin
      remote: git@github.com:jsavko/Drone-CI-Test.git
      branch: pages
      local_ref: pages
      ssh_key:
        from_secret: key