kind: pipeline
type: docker
name: default

steps:
- name: build site
  image: squidfunk/mkdocs-material
  commands: mkdocs build
- name: git-push
  settings:
    branch: pages
    force: false
    commit: true