kind: pipeline
name: default

steps:
- name: test
  image: squidfunk/mkdocs-material
  commands:
  - pip install -r requirements.txt
  - mkdocs build

- name: update
  image: appleboy/drone-git-push
    branch: pages
    commit: true