kind: pipeline
name: default

steps:
- name: greeting
  image: python
  commands:
  - pip install -r requirements.txt
  - mkdocs build
  
- name: git-push
  settings:
    branch: pages
    force: false
    commit: true