kind: pipeline
name: default

workspace:
  path: /drone/src

steps:
- name: test
  image: squidfunk/mkdocs-material
  commands:
  - pip install -r requirements.txt
  - mkdocs build
  - rm -R docs
  - mv site docs

- name: git-pushs
  image: appleboy/drone-git-push
  settings:
    branch: pages
    remote: git@github.com:jsavko/Drone-CI-Test.git
    force: true
    commit: true
    path: /drone/src/site
    ssh_key:
      from_secret: GIT_KEY
    commit_message: "Update readme to new version [CI SKIP]"

trigger:
  branch:
  - main
