kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: python
  commands: 
  - pip install requirements.txt
  - mkdocs build
  
- name: git-push
  settings:
    branch: pages
    force: false
    commit: true