kind: pipeline
name: default

steps:
- name: test
  image: squidfunk/mkdocs-material
  commands:
  - pip install -r requirements.txt
  - mkdocs build

- name: update
  image: appleboy/drone-git-push
  remote_name: origin
  branch: pages
  local_ref: pages
  ssh_key:
    from_secret: key