kind: pipeline
type: docker
name: default

steps:

- name: build site
  image: docker.io/squidfunk/mkdocs-material/latest
  commands: mkdocs build

- name: git-push
  settings:
    branch: pages
    force: false
    commit: true