site_name: My Docs
theme:
  name: material
  
nav:
    - Home: index.md
    - About: about.md
    - Op: op.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets