site_name: My Docs
theme:
  name: material
nav:
    - Home: index.md
    - About: about.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format